### ISSUE TITLE
Arc startup fails

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#1047]
With latest version, Arc fails to run:
```
loopback-example-app rand$ slc arc
Run `npm install loopback-explorer` to enable the LoopBack explorer
Loading workspace /Users/rand/StrongLoop/loopback-example-app
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:53830/#/

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/node_modules/loopback-explorer/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.header (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:717:10)
    at ServerResponse.send (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:235:15)
    at ServerResponse.send (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/express/lib/response.js:134:21)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/proxy/server.js:35:25
    at Labeled.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/proxy/build-client.js:29:7)
    at Labeled.emit (events.js:95:17)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
Rands-MacBook-Air:loopback-example-app rand$ 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
```

Here is what I see:

![arc bug](https://cloud.githubusercontent.com/assets/2925364/6257963/52d9b700-b779-11e4-821a-16f988e4ded8.png)

Before running, I did `slc update`.   Version info:

```
$ slc version
strongloop v2.10.3 (node v0.10.32)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── node-inspector@0.7.4
├── strong-deploy@1.1.4 (5e25e21)
├── strong-pm@1.7.2 (315d448)
├── strong-registry@1.1.4 (aab3dbb)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.2 (96a7f70)
```

**Comment by cgole** [comment]
https://github.com/strongloop/strong-arc/issues/1009

**Comment by ritch** [comment]
Fixed by https://github.com/strongloop/strong-mesh-client/pull/15

**Comment by ritch** [comment]
Fixed in https://github.com/strongloop/strong-mesh-client/releases/tag/v1.3.4
