### ISSUE TITLE
Arc Javascript Error - Process Manager not loading

### ISSUE THREAD

**Issue by sgentile** [strongloop/strong-arc#1104]
I'm unable to use the Arc tool for the Process Manager 

the error:
$scope.mesh = require('strong-mesh-client')('http://' + $location.host() + ':' + $location.port() + '/manager');

console:
ReferenceError: require is not defined
    at new <anonymous> (http://localhost:55745/scripts/modules/manager/manager.controllers.js:9:19)
    at invoke (http://localhost:55745/scripts/vendor/angular/angular.js:3708:17)
    at Object.instantiate (http://localhost:55745/scripts/vendor/angular/angular.js:3719:23)
    at http://localhost:55745/scripts/vendor/angular/angular.js:6770:28
    at http://localhost:55745/scripts/vendor/angular/angular-ui-router.js:2797:28
    at nodeLinkFn (http://localhost:55745/scripts/vendor/angular/angular.js:6224:13)
    at compositeLinkFn (http://localhost:55745/scripts/vendor/angular/angular.js:5634:15)
    at publicLinkFn (http://localhost:55745/scripts/vendor/angular/angular.js:5539:30)
    at updateView (http://localhost:55745/scripts/vendor/angular/angular-ui-router.js:2733:23)
    at http://localhost:55745/scripts/vendor/angular/angular-ui-router.js:2697:11 <div ui-view="" autoscroll="false" class="app-module-container ng-scope">

**Comment by sgentile** [comment]
problem was with my permissions -
