### ISSUE TITLE
New install:  EACCES error trying to write generated-instructions.json (to /usr/lib)

### ISSUE THREAD

**Issue by drmikecrowe** [strongloop/strong-arc#1110]
When running "slc arc" in a new project, I keep getting the error message below. 

Installed using the standard install instructions: http://docs.strongloop.com/display/SL/Installing+StrongLoop

```
Error: EACCES, permission denied '/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-boot/generated-instructions.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at bundleInstructions (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-boot/lib/bundler.js:99:6)
    at addInstructionsToBrowserify (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-boot/lib/bundler.js:16:3)
    at Function.exports.compileToBrowserify (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-boot/index.js:140:3)
    at buildBrowserBundle (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/proxy/build-client.js:19:10)
    at /usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-mesh-client/proxy/server.js:33:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/route.js:91:3)
```

**Comment by nwwells** [comment]
+1

**Comment by nwwells** [comment]
$ slc --version
strongloop v3.0.6 (node v0.12.0)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├── strong-deploy@1.2.0 (1c78f8d)
├── strong-pm@3.1.9 (9579431)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.0.3 (b23e63f)
├─┬ strong-supervisor@1.5.1 (d9364bd)
│ └── strong-agent@1.4.0
├── generator-loopback@1.9.0 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
