### ISSUE TITLE
App controller doesnt work. 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1138]
App controller start is broken because of this. https://github.com/strongloop/strong-arc/blob/master/build-deploy/common/models/deployment.js#L14

**Comment by cgole** [comment]
changing cluster size to 1 doesnt resolve the issue. Something seems to crash pm. The app starts and then changes status back to stop.

Steps to repro -

create simple loopback app
start arc
click on app controller to start app
Expected - App should start
Actual - App tries to start and then fails.

output from console in Debug mode  - https://gist.github.com/cgole/a18848d2d3ab28ce76c7

**Comment by sam-github** [comment]
It's supposed to be `-1`!

https://github.com/strongloop/strong-supervisor/pull/83

**Comment by seanbrookes** [comment]
was app controller tested after this update?

it works in production and I have been using it locally without any problem up until now but I switched to master and it is not working for me now.

Sam did you look at the output Chandrika linked to to see if it makes any sense to you?
@sam-github

**Comment by cgole** [comment]
I tested it after the update.  @seanbrookes  refer to -https://github.com/strongloop/strong-arc/issues/1138#issuecomment-89032951 
Like @sam-github  said, the cluster size should be -1 and so that did not fix the issue. App controller is broken.

**Comment by ritch** [comment]
@seanbrookes @sam-github 

I've reproduced the issue. I'm pretty sure this isn't caused by the http proxy / embedded pm. I see that the browser is sending a

```js
{cmd: 'stop'}
```

action after I hit play and the app starts successfully. Any idea why? I'm assigning to @seanbrookes to take a look. If this ends up to be something I can help with let me know, but I'm not sure what else to look into ATM.

**Comment by seanbrookes** [comment]
there is a start attempt limit put in to avoid run away problems with broken apps

it was only set to 5 (about 3.5 seconds) so the app didn't have time to start

I bumped it up to 50 (approx 35 seconds) which should be plenty of time - plus Sam has added  a single shot element to the pm start so things should be good here


PR: https://github.com/strongloop/strong-arc/pull/1180

**Comment by cgole** [comment]
It is now failing on this error - 

/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:3734
2015-04-13T17:50:29.555Z pid:80130 worker:1             throw e;
2015-04-13T17:50:29.555Z pid:80130 worker:1                   ^
2015-04-13T17:50:29.555Z pid:80130 worker:1 Error: Line 19: Unexpected token }
2015-04-13T17:50:29.555Z pid:80130 worker:1     at throwError (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:1846:21)
2015-04-13T17:50:29.555Z pid:80130 worker:1     at throwUnexpected (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:1904:9)
2015-04-13T17:50:29.555Z pid:80130 worker:1     at expect (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:1913:13)
2015-04-13T17:50:29.555Z pid:80130 worker:1     at parseArguments (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2237:17)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2300:24)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parsePostfixExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2341:16)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseUnaryExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2368:20)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseBinaryExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2489:16)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseConditionalExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2549:16)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseAssignmentExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2575:23)
2015-04-13T17:50:29.556Z pid:80130 worker:1     at parseExpression (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-trace/node_modules/strong-trace-instrument/node_modules/strong-trace-scopetracer/node_modules/strong-trace-scopenodes/node_modules/esprima/esprima.js:2601:16)
2015-04-13T17:50:29.568Z pid:80129 worker:0 ERROR supervisor worker id 1 (pid 80130) accidental exit with 8
Stop Runner: child 80129 commit default/local-directory in /Users/chandrikagole/workspace/repos/strongloop-images
2015-04-13T17:51:08.010Z pid:80129 worker:0 WARN received SIGTERM, shutting down
2015-04-13T17:51:08.011Z pid:80129 worker:0 INFO supervisor size set to undefined
2015-04-13T17:51:08.012Z pid:80129 worker:0 INFO supervisor stopped

**Comment by seanbrookes** [comment]
hmm, that looks like a poblem with strong-trace, not with App Controller.  I'll test again and check with Krishna if I see the same error.

**Comment by cgole** [comment]
Steps to repro are the same as before - 

create simple loopback app
start arc
click on app controller to start app
Expected - App should start
Actual - App tries to start and then fails.

output from console in Debug mode - https://github.com/strongloop/strong-arc/issues/1138#issuecomment-92444463

**Comment by cgole** [comment]
verified
