### ISSUE TITLE
slc arc --> TypeError: undefined is not a function at C:\...\strong-mesh-client\proxy\boot\manager-host.js:43:16

### ISSUE THREAD

**Issue by Acaspita** [strongloop/strong-arc#1256]
After running slc arc in the folder of a loopback app, I get this: (Under Windows 8.1)
```
Loading workspace C:\Users\Acaspita\Documents\Projects\Loopback-App
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:4583/#/

C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\proxy\boot\manager-host.js:43
        return cb(err);
               ^
TypeError: undefined is not a function
    at C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client\proxy\boot\manager-host.js:43:16
    at null._onTimeout (C:\Users\Acaspita\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-datasource-juggler\lib\datasource.js:2036:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by seanbrookes** [comment]
This may have been resolved.  What version of Arc are you running?

**Comment by sam-github** [comment]
@Acaspita still an issue, or can we close this?

**Comment by Acaspita** [comment]
I lost track of this. If I encounter with something akin again, report will I do. Close it please.
