### ISSUE TITLE
broken integration test on arc

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1317]
Need to talk to @bajtos to find out why this test isn't passing. See also #1316.

**Comment by anthonyettinger** [comment]
@bajtos this test won't pass for me. Not sure why.

We upgraded vendor package manage to use bower.

https://github.com/strongloop/strong-arc/blob/master/client/test/integration/spec/property/property.services.ispec.js

**Comment by bajtos** [comment]
So what's the error message you are seeing? Is there anything special reported to console log?

**Comment by anthonyettinger** [comment]
```
[08:49:27] Starting 'test-client-integration'...
Embedded Process Manager [(none)]:  starting
Arc running at http://localhost:9800
Running node_modules/.bin/karma start --single-run --browsers PhantomJS client/test/integration/karma.integration.js
WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
INFO [karma]: Karma v0.12.32 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
sl-pm.js: StrongLoop PM v3.2.1 (API v5.1.1) listening on port `49578`
sl-pm.js: listen on 49578, work base is `/Users/aettinger/projects/strongloop/strong-arc/.strong-pm`
Embedded Process Manager [1423]:  started
Embedded Process Manager [1423]:  using port 49578
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket CA82o1iqonn7Pha9AAAA with id 43322831
ERROR: 'TypeError: Requested keys of a value that is not an object.
    at keys (http://localhost:9876/base/node_modules/es5-shim/es5-shim.js?39e9e5c123615b69b09f51a7a205c54ed9e1634a:798)
    at http://localhost:9876/base/client/www/scripts/modules/property/property.services.js?398b979a1b896b780cfc7e605a89d42d3fafd1dd:110
    at forEach (http://localhost:9876/base/node_modules/es5-shim/es5-shim.js?39e9e5c123615b69b09f51a7a205c54ed9e1634a:455)
    at http://localhost:9876/base/client/www/scripts/modules/property/property.services.js?398b979a1b896b780cfc7e605a89d42d3fafd1dd:119
    at processQueue (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:13248)
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:13264
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:14466
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:14282
    at http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:14571
    at done (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:9698)
    at completeRequest (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:9888)
    at requestLoaded (http://localhost:9876/base/client/www/scripts/vendor/angular/angular.js?1061b10c86c20aae22472741139f553995ce2951:9833)'

Start:
  modelPropertyTypes
    ✖ "before each" hook

Finished in 0.146 secs / 0.12 secs

SUMMARY:
✔ 0 tests completed
✖ 1 tests failed

FAILED TESTS:
  modelPropertyTypes
    ✖ "before each" hook
      PhantomJS 1.9.8 (Mac OS X)
    TypeError: Requested keys of a value that is not an object.
        at keys (/Users/aettinger/projects/strongloop/strong-arc/node_modules/es5-shim/es5-shim.js:798)
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/modules/property/property.services.js:110
        at forEach (/Users/aettinger/projects/strongloop/strong-arc/node_modules/es5-shim/es5-shim.js:455)
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/modules/property/property.services.js:119
        at processQueue (/Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:13248)
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:13264
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:14466
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:14282
        at /Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:14571
        at done (/Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:9698)
        at completeRequest (/Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:9888)
        at requestLoaded (/Users/aettinger/projects/strongloop/strong-arc/client/www/scripts/vendor/angular/angular.js:9833)

[08:49:33] 'test-client-integration' errored after 6.16 s
[08:49:33] Error: Failed with exit code 1
    at ChildProcess.<anonymous> (/Users/aettinger/projects/strongloop/strong-arc/gulpfile.js:272:16)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
[08:49:33] 'test' errored after 10 s
[08:49:33] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/aettinger/projects/strongloop/strong-arc/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/aettinger/projects/strongloop/strong-arc/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/aettinger/projects/strongloop/strong-arc/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/aettinger/projects/strongloop/strong-arc/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/aettinger/projects/strongloop/strong-arc/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/aettinger/projects/strongloop/strong-arc/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:117:20)
```

**Comment by bajtos** [comment]
The error log points to https://github.com/strongloop/strong-arc/blob/db08ddd9e1a8242056de0125a1127bd729d60253/client/www/scripts/modules/property/property.services.js#L110. It looks like the result of `ModelProperty.getAvailableTypes()` is no longer an array of objects. Could it be a consequence of upgrading angular from 1.2 to 1.3?

**Comment by anthonyettinger** [comment]
Most likely, I guess the question is what should it be? I log it out and I get undefined.

**Comment by bajtos** [comment]
> Most likely, I guess the question is what should it be? I log it out and I get undefined.

It should be an array of strings, see https://github.com/strongloop/loopback-workspace/blob/master/models/model-property.js#L14-L37. 

Remember that `ModelProperty.getAvailableTypes()` is an ngResource method, it returns an array that is populated later after the server responded back. I think you need to call `ModelProperty.getAvailableTypes().$promise.then(console.log.bind(console))` instead of `console.log(ModelProperty.getAvailableTypes()`.

**Comment by anthonyettinger** [comment]
I tried this, but its just an empty array:
```
  beforeEach(function() {
    return inject(function(_modelPropertyTypes_) {
      console.log('FOO', _modelPropertyTypes_); //empty array (no methods)
      modelPropertyTypes = _modelPropertyTypes_;
      return modelPropertyTypes.getAvailableTypes().$promise; //undefined
    });
  });
```

**Comment by anthonyettinger** [comment]
@bajtos

**Comment by bajtos** [comment]
> I don't understand where `_modelPropertyTypes_` comes from.

See https://docs.angularjs.org/api/ngMock/function/angular.mock.inject#resolving-references-underscore-wrapping-

I'll run the tests myself to see if I can fix the problem.

**Comment by bajtos** [comment]
Well, the test is passing for me on the current master. Can you try to clean `client/www/scripts/vendor`, run `bower install && gulp build` and then try to run the test again?

**Comment by anthonyettinger** [comment]
still failing for me:

```
FAILED TESTS:
  modelPropertyTypes
    ✖ "before each" hook
      PhantomJS 1.9.8 (Mac OS X)
    TypeError: Requested keys of a value that is not an object.
```

**Comment by chandadharap** [comment]
Why is this at all assigned to @altsang?!

**Comment by bajtos** [comment]
I have troubleshooted this with @anthonyettinger via ScreenHero. The test is passing in Chrome, but failing in PhantomJS. We found a fix, I assume @anthonyettinger will eventually land it.

Let's reassign back to @anthonyettinger.

**Comment by chovy** [comment]
Merged here: https://github.com/strongloop/strong-arc/pull/1379
