### ISSUE TITLE
slc arc throws error 'Cannot find module 'minkelite'', but seems working after this error

### ISSUE THREAD

**Issue by cgwic** [strongloop/strong-arc#1340]
D:\work\tuts\node-stuff\loopback-example-passport>slc arc
Loading workspace D:\work\tuts\node-stuff\loopback-example-passport
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:61750/#/
module.js:339
    throw err;
    ^
Error: Cannot find module 'minkelite'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-pm\node_modules\strong-mesh-models\server\server.js:7:17)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Embedded Process Manager [10952]:  exited with code1
Embedded Process Manager [10952]:  crashed
TypeError: res.setStatus is not a function
    at ProcessManager.proxyRequest (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\process-manager\process-manager.js:99:11)
    at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\process-manager\server.js:19:6
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\index.js:302:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\index.js:270:7
    at Function.proto.process_params (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\index.js:321:12)
    at next (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\index.js:261:10)
    at expressInit (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\middleware\init.js:23:5)
    at Layer.handle [as handle_request] (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\layer.js:82:5)
    at trim_prefix (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\express\lib\router\index.js:302:13)

win7x64
strongloop installed with warnings about optional components:
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing strong-fork-syslog@1.2.3
npm WARN optional dep failed, continuing heapdump@0.3.5

strongloop v4.0.4 (node v2.0.1)
├── strong-arc@1.4.0 (27dd5c8)
├── strong-build@2.0.2 (3221b91)
├── strong-deploy@2.2.2 (13baab4)
├── strong-pm@4.2.0 (8713f6a)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.1.0 (04195e6)
├─┬ strong-supervisor@2.0.0 (4c3ac51)
│ └── strong-agent@1.6.0
├── generator-loopback@1.9.1 (5219ef1)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

iojs --version
v2.0.1

**Comment by cgwic** [comment]
sorry missed ```npm WARN optional dep failed, continuing minkelite@1.1.1``` in output
