### ISSUE TITLE
Getting 500 Error Trying to log into ARC locally

### ISSUE THREAD

**Issue by stevenatkin** [strongloop/strong-arc#1599]
I am getting a 500 error here is the output from the browser console.

```
{"error":{"name":"Error","status":404,"message":"Shared class \"Subscription\" has no method handling GET /login?include=user","statusCode":404,"stack":"Error: Shared class \"Subscription\" has no method handling GET /login?include=user\n    at restRemoteMethodNotFound (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:328:17)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)\n    at /usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)\n    at next (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)\n    at Function.handle (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)\n    at router (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)"}}
```

**Comment by stevenatkin** [comment]
It looks like the issue is permissions. The server should probably generate an error message in the ARC console.
```
error: {name: "Error", status: 500,…}
code: "EACCES"
errno: -13
message: "EACCES: permission denied, open '/Users/Steve/.strongloop/licenses.json'"
name: "Error"
path: "/Users/Steve/.strongloop/licenses.json"
stack: "Error: EACCES: permission denied, open '/Users/Steve/.strongloop/licenses.json'↵ at Error (native)"
status: 500
syscall: "open"
```

**Comment by jtary** [comment]
@stevenatkin have you tried modifying the file or folder permissions?

I agree that Arc should be reporting a more useful case if that is the cause of this, just want to confirm.

**Comment by stevenatkin** [comment]
I changed the permissions and that resolved the issue.

**Comment by jtary** [comment]
Ok, thanks. The error should be cause and an error reported to the console for Arc.

**Comment by A11oW** [comment]
@stevenatkin I have similar problem https://github.com/strongloop/strong-arc/issues/1729. How do you resolved it?
