### ISSUE TITLE
Alot of Errors when trying to install ARC on OSX

### ISSUE THREAD

**Issue by daslicht** [strongloop/strong-arc#1654]
When I try to install Strang-Arc on OS X 10.11.1 (Node4.2.1) as described here:

IDEA?

```
https://strongloop.com/node-js/arc/
```
I get those Errors and Warnings: 

```
npm WARN peerDependencies The peer dependency sshpk@^1.4.6 included from http-signature will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm WARN deprecated react-tools@0.10.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:2:
../compat-inl.h:288:37: error: no member named 'StartCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StartProfiling'?
  return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                    ^~~~~~~~~~~~~~~~~
                                    StartProfiling
/Users/daslicht/.node-gyp/4.2.1/include/node/v8-profiler.h:201:8: note: 'StartProfiling' declared here
  void StartProfiling(Local<String> title, bool record_samples = false);
       ^
In file included from ../syslog.cc:2:
../compat-inl.h:294:37: error: no member named 'StopCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StopProfiling'?
  return isolate->GetCpuProfiler()->StopCpuProfiling(title);
                                    ^~~~~~~~~~~~~~~~
                                    StopProfiling
/Users/daslicht/.node-gyp/4.2.1/include/node/v8-profiler.h:207:15: note: 'StopProfiling' declared here
  CpuProfile* StopProfiling(Local<String> title);
              ^
In file included from ../syslog.cc:2:
../compat-inl.h:310:55: error: no viable conversion from 'v8::Local<v8::String>' to 'v8::ActivityControl *'
  return isolate->GetHeapProfiler()->TakeHeapSnapshot(title);
                                                      ^~~~~
/Users/daslicht/.node-gyp/4.2.1/include/node/v8-profiler.h:487:24: note: passing argument to parameter 'control' here
      ActivityControl* control = NULL,
                       ^
3 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing strong-fork-syslog@1.2.3


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-control-channel/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/babel-core requires minimatch@'^2.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/minimatch,
npm WARN unmet dependency which is version 3.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/escope requires estraverse@'^3.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/estraverse,
npm WARN unmet dependency which is version 4.1.1
npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/vow-fs requires glob@'^4.3.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/jscs/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
```

**Comment by raymondfeng** [comment]
node-syslog is an optional dependency (https://github.com/schamane/node-syslog) and it has not been ported to Node 4.x yet. You can safely ignore the error and the installation should be fine.

@sam-github @rmg Any plan to have a new release of syslog?

**Comment by daslicht** [comment]
the installation do not finish, at least its not working after ist has been finished

**Comment by daslicht** [comment]
Switching Node to v0.10.40 works for me

**Comment by rmg** [comment]
@raymondfeng we have already replaced node-syslog with strong-fork-syslog, and then replaced it with modern-syslog. The problem is Arc currently depends on an older version of strong-pm that still depends on strong-fork-syslog.
