### ISSUE TITLE
Authentication attempt failed

### ISSUE THREAD

**Issue by A11oW** [strongloop/strong-arc#1729]
When try StrongLoop Arc sign in `http://localhost:50949/api/Subscriptions/login?include=user` return 500
```
{"error":{"name":"Error","status":500,"message":"write EPROTO 140735284158464:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:\n","code":"EPROTO","errno":"EPROTO","syscall":"write","stack":"Error: write EPROTO 140735284158464:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:\n\n    at exports._errnoException (util.js:856:11)\n    at WriteWrap.afterWrite (net.js:763:14)"}}
```

**Comment by A11oW** [comment]
That happens if `common/models` move in `server/` folder, like this `server/models`. Where I can configurate that?
`server/model-config.json` does not affect for `slc arc`?
