### ISSUE TITLE
Type for AnonymousModel (or Model or models) is set as null, app will not start from failure in model-builder.js

### ISSUE THREAD

**Issue by uhrohraggy** [strongloop/strong-arc#537]
{ modelBuilder: 
   { models: 
      { Model: [Object],
        PersistedModel: [Object],
        Email: [Object],
        Application: [Object],
        AnonymousModel_0: [Object],
        AnonymousModel_1: [Object],
        AnonymousModel_2: [Object],
        AnonymousModel_3: [Object],
        AnonymousModel_4: [Object],
        AnonymousModel_5: [Object],
        AccessToken: [Object],
        RoleMapping: [Object],
        Role: [Object],
        ACL: [Object],
        Scope: [Object],
        User: [Object],
        Change: [Object],
        Checkpoint: [Object],
        admin: [Object],
        Audience: [Object],
        CommunicationChannel: [Object],
        Country: [Object],
        Department: [Object],
        Group: [Object],
        Institution: [Object],
        Zipcode: [Object],
        AnonymousModel_6: [Object] },
     definitions: 
      { Model: [Object],
        PersistedModel: [Object],
        Email: [Object],
        AnonymousModel_2: [Object],
        AnonymousModel_3: [Object],
        AnonymousModel_1: [Object],
        AnonymousModel_4: [Object],
        AnonymousModel_0: [Object],
        AnonymousModel_5: [Object],
        Application: [Object],
        AccessToken: [Object],
        RoleMapping: [Object],
        Role: [Object],
        ACL: [Object],
        Scope: [Object],
        User: [Object],
        Change: [Object],
        Checkpoint: [Object],
        admin: [Object],
        Change: [Object],
        Checkpoint: [Object],
        admin: [Object],
        Audience: [Object],
        CommunicationChannel: [Object],
        Country: [Object],
        Department: [Object],
        Group: [Object],
        Institution: [Object],
        Zipcode: [Object],
        AnonymousModel_6: [Circular] },
     mixins: { modelBuilder: [Circular], mixins: {} },
     defaultModelBaseClass: 
      { [Function: ModelConstructor]
        setMaxListeners: [Function],
        emit: [Function],
        addListener: [Function],
        on: [Function],
        once: [Function],
        removeListener: [Function],
        removeAllListeners: [Function],
        listeners: [Function],
        super_: [Object],
        defineProperty: [Function],
        getPropertyType: [Function],
        isHiddenProperty: [Function],
        mixin: [Function],
        getDataSource: [Function],
        afterInitialize: null,
        beforeValidate: null,
        afterValidate: null,
        beforeSave: null,
        afterSave: null,
        beforeCreate: null,
        afterCreate: null,
        beforeUpdate: null,
        afterUpdate: null,
        beforeDestroy: null,
        afterDestroy: null,
        validatesPresenceOf: [Function],
        validatesAbsenceOf: [Function],
        validatesLengthOf: [Function],
        validatesNumericalityOf: [Function],
        validatesInclusionOf: [Function],
        validatesExclusionOf: [Function],
        validatesFormatOf: [Function],
        validate: [Function],
        validateAsync: [Function],
        validatesUniquenessOf: [Function],
        getter: {},
        setter: {},
        definition: [Object],
        settings: [Object],
        forEachProperty: [Function],
        attachTo: [Function],
        extend: [Function],
        registerProperty: [Function],
        setup: [Function],
        _ACL: [Function: getACL],
        checkAccess: [Function],
        _getAccessTypeForMethod: [Function],
        getApp: [Function],
        remoteMethod: [Function],
        disableRemoteMethod: [Function],
        belongsToRemoting: [Function],
        hasOneRemoting: [Function],
        hasManyRemoting: [Function],
        scopeRemoting: [Function],
        nestRemoting: [Function],
        ValidationError: [Object],
        sharedClass: [Object],
        sharedCtor: [Object],
        beforeRemote: [Function],
        afterRemote: [Function] },
     _nameCount: 6 },
  name: 'AnonymousModel_6',
  rawProperties: { type: null },
  settings: { anonymous: true, idInjection: false, strict: false },
  relations: [],
  **properties: { type: { type: null } },**
  _ids: [] }

/home/user2/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-builder.js:374
      throw new Error('Invalid type for property ' + propertyName);
            ^
Error: Invalid type for property type
    at Function.ModelClass.registerProperty (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-builder.js:374:13)
    at ModelBuilder.defineClass [as define](/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-builder.js:442:16)
    at ModelBuilder.resolveType (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-builder.js:626:19)
    at ModelDefinition.build (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-definition.js:221:34)
    at ModelDefinition.defineProperty (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-definition.js:254:8)
    at ModelBuilder.defineProperty (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/model-builder.js:485:27)
    at DataSource.defineProperty (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/datasource.js:741:21)
    at DataSource.defineForeignKey (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/datasource.js:1730:10)
    at Function.RelationDefinition.belongsTo (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1132:26)
    at Function.RelationMixin.belongsTo (/home/uhrohraggy/Documents/apps/integration/node_modules/loopback-datasource-juggler/lib/relations.js:123:29

**Comment by sam-github** [comment]
@uhrohraggy is this still true?
