### ISSUE TITLE
Fresh install of Studio beta R2 gives error on "Test Connection"

### ISSUE THREAD

**Issue by slgoldberg** [strongloop/strong-arc#571]
I tried two separate environments and got the same failure on both.

Steps to repeat:
0. Running node v0.10.29 on Debian Wheezy distro.
1. Install fresh version of `loopback-extended-API` and `strong-studio` and :
    `% git clone https://github.com/strongloop/loopback-example-extendedAPI.git`
    `% npm install -g http://get-studio.strongloop.com/strong-studio.tgz`
2. Run `strong-studio`:
    `% strong-studio`
3. Go to web browser and navigate to any existing datasource.
4. Click `Test Connection` and observe failure:
    `Cannot call method 'apply' of undefined`

The same error appears but with a stack trace to ease debugging, if you click `discover models` for the datasource instead. The error message is the same as above, and the stack trace is below:

```
TypeError: Cannot call method 'apply' of undefined
    at invoke (/usr/lib/node_modules/strong-studio/node_modules/loopback-workspace/bin/datasource-invoke.js:55:20)
    at process.dataSourceName (/usr/lib/node_modules/strong-studio/node_modules/loopback-workspace/bin/datasource-invoke.js:7:3)
    at process.g (events.js:180:16)
    at process.emit (events.js:98:17)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
```

The failure is independent of connector type. It will fail in the same way above with any connector type, e.g. mysql, in-memory db, etc. However, in the case I'm trying most desperately to get working, which is to avail myself of the awesome mysql discovery UI to create a model based on an existing mysql database, I'm stuck because of this error.

And to be clear, I am able to access (both read and write) all my defined models that use these same datasources in the node application. In other words, the API explorer works just fine for reading and writing, so it's not a configuration issue.

I'm wondering if perhaps it's a version compatibility issue that's not automatically handled by npm?  I see others referencing node 0.11.x but I'm using  0.10.x.  I am nervous about getting into other issues if I try to force update to 0.11 but if that's the solution, then so be it. Please confirm if so or let me know if there's a work-around so I can stay on 0.10 (if that's actually the issue).  There was nothing in the known issues nor in the recent bugs or discussions that I could find, so that's why I'm filing it. And once I verified that it worked with a fresh install, that was clearly something worth reporting to avoid more questions as others try to follow the instructions as I did today.

Thanks very much.

**Comment by kodecraft** [comment]
I have the same issue. I am using strong arc (previously named strong studio) - node (0.10.33), npm (2.1.16) also on Debian7. Whether mysql or in-memory db, I get the following error statements when testing connection of the datasource:

Oops! Something is wrong
Cannot read property 'mysql-db' of undefined
Show/hide details
Message: Cannot read property 'mysql-db' of undefined
Request: /workspace/api/DataSourceDefinitions/server.mysql-db/testConnection
Staus: 500
```javascript
TypeError: Cannot read property 'mysql-db' of undefined
    at invoke (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/bin/datasource-invoke.js:45:25)
    at process.dataSourceName (/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback-workspace/bin/datasource-invoke.js:7:3)
    at process.g (events.js:180:16)
    at process.emit (events.js:98:17)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
```

**Comment by kodecraft** [comment]
I looked at the code for datasource-invoke.js and realised that the object 'app' may not have been exported so I went to server.js and made sure the following was set up:
``
var app = module.exports = loopback();
``
Then it started working.

Hope this helps.
