### ISSUE TITLE
EE_WRITE Error when migrating a model to mysql

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#599]
Not sure if this is reproducible, but after running into this, I had to restart arc. It was stuck at migrating

Oops! Something is wrong
EE_WRITE: Error writing file './coffee/book.frm' (Errcode: 28)
Show/hide details
Message: EE_WRITE: Error writing file './coffee/book.frm' (Errcode: 28)
Request: /workspace/api/DataSourceDefinitions/server.mysql/autoupdate
Staus: 500

Error: EE_WRITE: Error writing file './coffee/book.frm' (Errcode: 28)
    at Query.Sequence._packetToError (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    --------------------
    at Protocol._enqueue (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.Connection.query (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:185:25)
    at runQuery (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/lib/mysql.js:153:16)
    at /Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/lib/mysql.js:199:7
    at Ping.onPing [as _callback](/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:94:5)
    at Ping.Sequence.end (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/chandrikagole/workspace/repos/test/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)

**Comment by vsmurali** [comment]
I am getting same error - OS : Wiindows7 : 

C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI>mysql --version
mysql  Ver 14.14 Distrib 5.5.25a, for Win32 (x86)

C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI>slc --version
strongloop v2.10.3 (node v0.10.28)
+-- strong-arc@1.0.4
+-- strong-build@1.0.3
+-- strong-supervisor@1.4.0
¦ +-- strong-agent@1.3.2
+-- node-inspector@0.7.4
+-- strong-deploy@1.1.3
+-- strong-pm@1.7.0
+-- strong-registry@1.1.4
+-- nodefly-register@0.3.3
+-- generator-loopback@1.7.1

Oops! Something is wrong
ER_ERROR_ON_RENAME: Error on rename of '.\murali_dev\#sql-2f24_17' to '.\murali_dev\employee' (errno: 150)
Show/hide details

    Message: ER_ERROR_ON_RENAME: Error on rename of '.\murali_dev\#sql-2f24_17' to '.\murali_dev\employee' (errno: 150)
    Request: /workspace/api/DataSourceDefinitions/server.MuraliMySQLDS/autoupdate
    Staus: 500
	
	Error: ER_ERROR_ON_RENAME: Error on rename of '.\murali_dev\#sql-2f24_17' to '.\murali_dev\employee' (errno: 150) 
	at Query.Sequence._packetToError (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:48:14) 
	at Query.ErrorPacket (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\sequences\Query.js:82:18) 
	at Protocol._parsePacket (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Protocol.js:271:23) 
	at Parser.write (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Parser.js:77:12) 
	at Protocol.write (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16) 
	at Socket.<anonymous> (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\Connection.js:82:28) 
	at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:745:14) at Socket.EventEmitter.emit (events.js:92:17) 
	at emitReadable_ (_stream_readable.js:407:10) -------------------- 
	at Protocol._enqueue (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Protocol.js:135:48) 
	at PoolConnection.Connection.query (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\Connection.js:185:25) 
	at runQuery (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\lib\mysql.js:153:16) 
	at C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\lib\mysql.js:199:7 at Ping.onPing [as _callback] 
	(C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\Pool.js:94:5) 
	at Ping.Sequence.end (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24) 
	at Ping.Sequence.OkPacket (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\sequences\Sequence.js:105:8) 
	at Protocol._parsePacket (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Protocol.js:271:23) 
	at Parser.write (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Parser.js:77:12) 
	at Protocol.write (C:\Users\Murali-dev\Desktop\scratchpad\tmpAPI\node_modules\loopback-connector-mysql\node_modules\mysql\lib\protocol\Protocol.js:39:16)
