### ISSUE TITLE
Unhelpful error message when the project cannot be started via supervisor

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#695]
1. Checkout strong-arc@e22c63d4
2. `npm install` (it runs `gulp build` under the hood)
2. `slc arc` (the globally installed one)
3. Select "build and deploy"
4. Select git deploy
5. Click on "Build", wait for the build to finish
6. Copy the port number of the embedded process manager as printed in the console output of `slc arc` and fill it in the UI, use `localhost` as the hostname and `4` for the number of processes
6. Click on "Deploy", wait for the message "Successfully deployed using git"
6. Check the console output of `slc arc`:

  ```
2014-12-10T18:32:53.376Z pid:23615 worker:0 INFO supervisor started worker 44 (pid 23663)
2014-12-10T18:32:53.559Z pid:23663 worker:44 module.js:340
2014-12-10T18:32:53.559Z pid:23663 worker:44     throw err;
2014-12-10T18:32:53.559Z pid:23663 worker:44           ^
2014-12-10T18:32:53.560Z pid:23663 worker:44 Error: Cannot find module '/Users/bajtos/src/strong/arc/.strong-pm/work/62c866cfd66e8b34217871842aca3732a795bc57.1418236267044'
2014-12-10T18:32:53.560Z pid:23663 worker:44     at Function.Module._resolveFilename (module.js:338:15)
2014-12-10T18:32:53.560Z pid:23663 worker:44     at Function.Module._load (module.js:280:25)
2014-12-10T18:32:53.560Z pid:23663 worker:44     at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:40:19)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at Module._compile (module.js:456:26)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at Object.Module._extensions..js (module.js:474:10)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at Module.load (module.js:356:32)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at Function.Module._load (module.js:312:12)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at Function.Module.runMain (module.js:497:10)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at startup (node.js:119:16)
2014-12-10T18:32:53.561Z pid:23663 worker:44     at node.js:906:3
Receive request {"cmd":"exit","id":44,"pid":23663,"suicide":false,"reason":8} by Runner: child 23615 commit default/test-deploy in /Users/bajtos/src/strong/arc/.strong-pm/work/62c866cfd66e8b34217871842aca3732a795bc57.1418236267044
2014-12-10T18:32:53.567Z pid:23615 worker:0 ERROR supervisor worker id 44 (pid 23663) accidental exit with 8
```

There are two problems:
 1. The UI does not provide any information about the failed startup (see also #693)
 2. The error message is cryptic and does not provide any hints for the user about what is wrong and how to fix the problem. 
 2. ~~The application was not started~~

**Comment by chandadharap** [comment]
Assigning back to @bajtos and @sam-github for FYI. @cgole need not verify this Its not clear if its fixed either. Last update is 3 months ago?

**Comment by bajtos** [comment]
There are follow-up issues (#693 and https://github.com/strongloop/strong-pm/issues/96) tracking the remaining work, this one can be closed.
