### ISSUE TITLE
arc should run app on an ephemeral port, and loopback boot should report the port it attempts to listen on

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-arc#716]
arc should set PORT=0 in environment when running pm, so that the app runs an ephemeral port (note that arc already detects the port listened on as reported by node, so this will work well when sean displays the app URL in the config start box)

This will probably required boot support, which probably treats a "falsy" process.env.PORT value as "use default", it will need to understand 0 as a valid value, and use an ephemeral.

This is important, because if the app can't run due to port conflicts, you just get this on the console:

```
sam@samtu:~/w/arc/my-app (master %) % node . 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at Server._listen2 (/home/sam/w/arc/my-app/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:71:23)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

Note that loopback boot doesn't report the port that it failed to listen on! Which makes this quite hard to debug. Failure to listen errors should always be accompanied by the port that was failed to listen on.

**Comment by chandadharap** [comment]
Removed bug label. This is a feature needed for being able to run Arc from Heroku.

**Comment by seanbrookes** [comment]
what does 'run Arc from Heroku' mean?
- are we porting slc commands to heroku commands or are we talking about a gui launch?

@altsang @anthonyettinger the closer we get to a 'pure' gui/browser Arc experience the more we have to consider mobile layouts and resolutions in the designs

**Comment by chandadharap** [comment]
gui launch.

**Comment by altsang** [comment]
@seanbrookes if there's a door - it'll be opened whether or not we want it to be opened or not - yes understood
