### ISSUE TITLE
API composer broken 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#767]
$ slc arc
Run `npm install loopback-explorer` to enable the LoopBack explorer
Loading workspace /private/tmp/loopback-example-app
Embedded Process Manager [(none)]:  starting
StrongLoop Arc is running here: http://localhost:49745/#/
slc arc: control listening on path `/private/tmp/loopback-example-app/pmctl`
slc arc: listen on 49752, work base is `/private/tmp/loopback-example-app/.strong-pm` with config `/private/tmp/loopback-example-app/.strong-pm/config`
Embedded Process Manager [49792]:  started
Embedded Process Manager [49792]:  using port 49752
Error: Cannot GET /api/PackageDefinitions/findOne?
    at raiseUrlNotFoundError (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request](/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:271:13)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:238:9
    at Function.proto.process_params (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:313:12)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:296:3)
    at next (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:190:10)
    at SendStream.error (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/node_modules/serve-static/index.js:103:7)
    at SendStream.emit (events.js:95:17)
Error: Cannot GET /api/PackageDefinitions/findOne?
    at raiseUrlNotFoundError (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/server/middleware/url-not-found.js:15:17)
    at Layer.handle [as handle_request](/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:271:13)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:238:9
    at Function.proto.process_params (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:313:12)
    at /usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:229:12
    at Function.match_layer (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:296:3)
    at next (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/lib/router/index.js:190:10)
    at SendStream.error (/usr/local/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/loopback/node_modules/express/node_modules/serve-static/index.js:103:7)
    at SendStream.emit (events.js:95:17)

**Comment by andrenventer** [comment]
I am not sure its the same problem:

What I did:

clean install --
slc loopback
slc loopback:model   ...  ACL ...  user email, name, surname in memory - custom plural users
slc arc
Loading workspace /Users/nomad/Projects/loopie
StrongLoop Arc is running here: http://localhost:64674/#/

Pressed PLAY

What I expected:
API endpoint with no entities - http://localhost:3000/users

What I got:
http://localhost:3000/users

Loopback
404 Error: Cannot GET /users
   at raiseUrlNotFoundError (/Users/nomad/Projects/loopie/node_modules/loopback/server/middleware/url-not-found.js:15:17)
   at Layer.handle [as handle_request] (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)
   at /Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)
   at /Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:618:15
   at next (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:256:14)
   at Function.handle (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)
   at router (/Users/nomad/Projects/loopie/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)

**Comment by Frondor** [comment]
Still broken

**Comment by desduvauchelle** [comment]
I have the same issue. 
I updated loopback to `strongloop v6.0.1` with node `v5.11.1`.
When running `Error: Cannot POST /api/Users/login` from the explorer. Any ideas?

**Comment by ketansp** [comment]
Did anyone get a solution?

**Comment by tatemz** [comment]
I have the same issue. My explorer shows my valid api routes and everything works on localhost (using ipv6 and `0.0.0.0`)

When I post the app to my server and browse to it by IP address, none of the api endpoints work. :-(

**Comment by ketansp** [comment]
Guys, 

Updating the loopback-boot package helped me get it working in my case. Not sure, but you can give it a try.

**Comment by phortonssf** [comment]
No bueno for me Updating the loopback-boot package.
