### ISSUE TITLE
windows tarfile deploy of loopback-connector-oracle to linux fails

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#788]
```
$ slc pm -l 7777
slc pm: control listening on path `/home/ec2-user/pmctl`
slc pm: listen on 7777, work base is `/home/ec2-user/.strong-pm` with config `/home/ec2-user/.strong-pm/config`
commit ee3d3dff53b2369f85dc17e7167f033ee699922d spawn `npm rebuild`...

> loopback-oracle-installer@1.2.1 install /home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-1.3.0.tar.gz
http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-1.3.0.tar.gz is now extracted to /home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules
child_process.js:1147
    throw errnoException(err, 'spawn');
          ^
Error: spawn EACCES
    at exports._errnoException (util.js:742:11)
    at ChildProcess.spawn (child_process.js:1147:11)
    at exports.spawn (child_process.js:980:9)
    at /home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/pkginstall.js:54:15
    at Extract.<anonymous> (/home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/lib/download.js:75:15)
    at Extract.emit (events.js:129:20)
    at DirWriter.<anonymous> (/home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/node_modules/tar/lib/extract.js:66:8)
    at DirWriter.emit (events.js:129:20)
    at end (/home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/node_modules/fstream/lib/writer.js:323:12)
    at /home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/node_modules/loopback-connector-oracle/node_modules/loopback-oracle-installer/node_modules/fstream/lib/writer.js:313:32

npm ERR! Linux 3.14.20-20.44.amzn1.x86_64
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "rebuild"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! loopback-oracle-installer@1.2.1 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-oracle-installer@1.2.1 install script.
npm ERR! This is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/.strong-pm/work/ee3d3dff53b2369f85dc17e7167f033ee699922d.1418449343737/npm-debug.log
commit ee3d3dff53b2369f85dc17e7167f033ee699922d spawn `npm rebuild`...

```

**Comment by raymondfeng** [comment]
https://github.com/strongloop/loopback-oracle-installer/pull/7 is merged

**Comment by sam-github** [comment]
@cgole can you verify that deploy from windows to linux now works?
