### ISSUE TITLE
App Controller enabled when not in node app dir

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-arc#925]
When I run Arc in a directory that is not the root directory of an app, Composer and Build&Deploy are disabled on the splash page, which makes sense.  But in Profiler and Metrics App Controller is still enabled, which is a bug.

I did this:
```
$ pwd
/Users/rand
$ slc arc
````

In splash page, choose **Profiler** or **Metrics**.
 
Click **Run**, I see the following in the console:

```
2015-01-21T18:57:11.871Z pid:2333 worker:0 INFO supervisor resized to 1
2015-01-21T18:57:12.085Z pid:2334 worker:1 module.js:340
2015-01-21T18:57:12.085Z pid:2334 worker:1     throw err;
2015-01-21T18:57:12.085Z pid:2334 worker:1           ^
2015-01-21T18:57:12.086Z pid:2334 worker:1 Error: Cannot find module '/Users/rand'
2015-01-21T18:57:12.086Z pid:2334 worker:1     at Function.Module._resolveFilename (module.js:338:15)
2015-01-21T18:57:12.086Z pid:2334 worker:1     at Function.Module._load (module.js:280:25)
2015-01-21T18:57:12.087Z pid:2334 worker:1     at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:40:19)
2015-01-21T18:57:12.087Z pid:2334 worker:1     at Module._compile (module.js:456:26)
2015-01-21T18:57:12.087Z pid:2334 worker:1     at Object.Module._extensions..js (module.js:474:10)
2015-01-21T18:57:12.087Z pid:2334 worker:1     at Module.load (module.js:356:32)
2015-01-21T18:57:12.087Z pid:2334 worker:1     at Function.Module._load (module.js:312:12)
2015-01-21T18:57:12.088Z pid:2334 worker:1     at Function.Module.runMain (module.js:497:10)
2015-01-21T18:57:12.089Z pid:2334 worker:1     at startup (node.js:119:16)
2015-01-21T18:57:12.089Z pid:2334 worker:1     at node.js:906:3
2015-01-21T18:57:12.094Z pid:2333 worker:0 ERROR supervisor worker id 1 (pid 2334) accidental exit with 8
2015-01-21T18:57:14.159Z pid:2333 worker:0 INFO supervisor started worker 2 (pid 2335)
2015-01-21T18:57:14.160Z pid:2333 worker:0 INFO supervisor resized to 1
2015-01-21T18:57:14.339Z pid:2335 worker:2 module.js:340
2015-01-21T18:57:14.339Z pid:2335 worker:2     throw err;
2015-01-21T18:57:14.340Z pid:2335 worker:2           ^
2015-01-21T18:57:14.342Z pid:2335 worker:2 Error: Cannot find module '/Users/rand'
2015-01-21T18:57:14.342Z pid:2335 worker:2     at Function.Module._resolveFilename (module.js:338:15)
2015-01-21T18:57:14.342Z pid:2335 worker:2     at Function.Module._load (module.js:280:25)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:40:19)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Module._compile (module.js:456:26)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Object.Module._extensions..js (module.js:474:10)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Module.load (module.js:356:32)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Function.Module._load (module.js:312:12)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at Function.Module.runMain (module.js:497:10)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at startup (node.js:119:16)
2015-01-21T18:57:14.343Z pid:2335 worker:2     at node.js:906:3
```

**Comment by cgole** [comment]
not an issue anymore. App controller is going away.

**Comment by seanbrookes** [comment]
wait, I don't thnk App Controller is going away.  the internal pm is going away but he the ui control will still map to the slc start pm (8701)

**Comment by crandmck** [comment]
Based on Sean's comment, I'll go ahead and re-open this so it doesn't get dropped.

**Comment by cgole** [comment]
@chandadharap ^^

**Comment by seanbrookes** [comment]
The actual change is to keep the App Controller but to wire it up to a more basic  node start type command, bypassing the pm altogether.
So technically the app controller 'should' work on projects outside LB as long as we can make sense of the 'start path/file'

**Comment by chandadharap** [comment]
This fixes it for the immediate. Replacing Controller behavior is a medium/long term.

**Comment by chandadharap** [comment]
@rmg this seems to be a CI issue. @sean to follow up.

**Comment by sam-github** [comment]
@jtary why did you assign to @crandmck ? Does it need docs? Did you mean Ryan, or @cgole ?

**Comment by jtary** [comment]
@sam-github I think it was a mistake, should have gone to @cgole.

**Comment by cgole** [comment]
verified
